//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina2019.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmpleados()
        {
            this.tblTabuladorSueldo = new HashSet<tblTabuladorSueldo>();
        }
    
        public int iIdEmpleado { get; set; }
        public Nullable<int> iIdPadron { get; set; }
        public Nullable<int> iIdPeriodoPago { get; set; }
        public Nullable<int> iIdDepartamento { get; set; }
        public Nullable<bool> lActivo { get; set; }
        public Nullable<System.DateTime> dtCreacion { get; set; }
        public Nullable<System.DateTime> dtModificacion { get; set; }
    
        public virtual tblDepartamentos tblDepartamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTabuladorSueldo> tblTabuladorSueldo { get; set; }
        public virtual tblPadronPersonas tblPadronPersonas { get; set; }
        public virtual tblPeriodosPago tblPeriodosPago { get; set; }
    }
}
