//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina2019.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPadronPersonas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPadronPersonas()
        {
            this.tblEmpleados = new HashSet<tblEmpleados>();
        }
    
        public int iIdPadron { get; set; }
        public string cNombre { get; set; }
        public string cApellido1 { get; set; }
        public string cApellido2 { get; set; }
        public string cDireccion { get; set; }
        public string cTelefono { get; set; }
        public Nullable<System.DateTime> dtCreacion { get; set; }
        public Nullable<System.DateTime> dtModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmpleados> tblEmpleados { get; set; }
    }
}
