//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina2019.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTabuladorSueldo
    {
        public int iIdTabuladorSueldo { get; set; }
        public Nullable<int> iIdEmpleado { get; set; }
        public Nullable<decimal> dSueldoDiario { get; set; }
        public Nullable<bool> lActivo { get; set; }
        public Nullable<System.DateTime> dtCreacion { get; set; }
        public Nullable<System.DateTime> dtModificacion { get; set; }
    
        public virtual tblEmpleados tblEmpleados { get; set; }
    }
}
